[features]
seeds = false
skip-lint = false

[programs.devnet]
myepicproject = "9W6XvJxFRhkKQRHPpwHDNn6kQo5n114UUjQt4Zng65BC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/dennis/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
